server:
    port: 8100

polling-bot:
  token: ${TIME_REPORT_BOT_TOKEN}
  name: ${TIME_REPORT_BOT_NAME}
  buttons:
    days: ["🔳 Текущий день", "🔳 Ввести день"]
    actions-menu: ["🔳 Отчитаться", "🔳 Установить оповещения", "🔳 Отпуск/больничный"]

projects-cache-scheduler:
  period: 600000

inline-bot:
  max-result: 30

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/reporting_bot?allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useTimezone=true&autoReconnect=true&interactiveClient=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      type: com.zaxxer.hikari.HikariDataSource
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

dump:
  cron: 0 0 21 * * 7 # воскресенье 21:00
  save-dir: dumps